### ISSUE TITLE
tkinter error

### ISSUE THREAD

**Issue by Eldino162** [bonchinchi/youtubeViewerBot#3]
File "c:\Users\hurem\OneDrive\Desktop\viewbot\watcherBot_macos.py", line 1, in <module>
    from tkinter import *
ModuleNotFoundError: No module named 'tkinter'

**Comment by RasPiPkr** [comment]
Hi @Eldino162,

I see your having an issue with running the code, tkinter is a built-in library and therefore should work.

I'm curious on how you are trying to run the code via command line or an editor?

I'm nothing to do with this youtube viewer but happy to help if I can :thumbsup:
